@extends('admin.layouts.sistema')

@section('content')
    <div class="container pb-4">
        <div class="text-center">
            <img class="logo-home" src="{{asset('img/logo.png')}}">
        </div>
        <div class="text-home pt-4 text-justify" id="home-title">
            <p>
                Bem vindo ao portal do Observatório do Consumidor. O Observatório do Consumidor é uma ferramenta criada para monitorar o perfil do consumidor e tendências de consumo de leite e derivados no Brasil, de forma dinâmica e de fácil visualização, através da análise do conteúdo postado em redes sociais.
            </p>
            <p>
                Confira abaixo a Nuvem de Palavras gerada com os tweets sobre leite e derivados.
            </p>
        </div>
        <div id="wordcloud"></div>
        @if(Auth::check())
            <div class="pt-4 d-flex justify-content-end">
                <button type="button" class="btn btn-outline-success" onclick="shareAsPng();"><i class="fas fa-download"></i></button>
            </div>
        @endif

    </div>

@endsection
@push('scripts')
    <script>
        var data = [
            {"x":"sorvete","value":81607,category:"Hábito de consumo"},
            {"x":"queijo","value":76620,category:"Hábito de consumo"},
            {"x":"chocolate","value":72908,category:"Hábito de consumo"},
            {"x":"leite","value":58255,category:"Hábito de consumo"},
            {"x":"bolo","value":46410,category:"Sem categoria"},
            {"x":"pizza","value":44441,category:"Hábito de consumo"},
            {"x":"batata","value":44338,category:"Hábito de consumo"},
            {"x":"carne","value":43074,category:"Sem categoria"},
            {"x":"fruta","value":41440,category:"Hábito de consumo"},
            {"x":"agua","value":40889,category:"Sem categoria"},
            {"x":"conquistar","value":40093,category:"Sem categoria"},
            {"x":"refri","value":39025,category:"Sem categoria"},
            {"x":"suco","value":38127,category:"Hábito de consumo"},
            {"x":"boca","value":35203,category:"Sem categoria"},
            {"x":"pao","value":28920,category:"Hábito de consumo"},
            {"x":"doce","value":28528,category:"Hábito de consumo"},
            {"x":"morango","value":25437,category:"Hábito de consumo"},
            {"x":"frita","value":21696,category:"Sem categoria"},
            {"x":"gas","value":20351,category:"Sem categoria"},
            {"x":"pra","value":19849,category:"Sem categoria"},
            {"x":"condensado","value":18622,category:"Sem categoria"},
            {"x":"frango","value":18482,category:"Hábito de consumo"},
            {"x":"maracuja","value":16699,category:"Hábito de consumo"},
            {"x":"laranja","value":16195,category:"Hábito de consumo"},
            {"x":"coca","value":14790,category:"Sem categoria"},
            {"x":"qualquer","value":14119,category:"Sem categoria"},
            {"x":"q","value":13148,category:"Sem categoria"},
            {"x":"comer","value":13006,category:"Sem categoria"},
            {"x":"uva","value":12030,category:"Hábito de consumo"},
            {"x":"creme","value":11830,category:"Sem categoria"},
            {"x":"manteiga","value":10873,category:"Hábito de consumo"},
            {"x":"cenoura","value":10416,category:"Hábito de consumo"},
            {"x":"limao","value":10167,category:"Hábito de consumo"},
            {"x":"catupiry","value":9869,category:"Sem categoria"},
            {"x":"branco","value":9664,category:"Características dos produtos"},
            {"x":"to","value":9565,category:"Sem categoria"},
            {"x":"fazer","value":9454,category:"Sem categoria"},
            {"x":"banana","value":9400,category:"Hábito de consumo"},
            {"x":"abacaxi","value":9353,category:"Hábito de consumo"},
            {"x":"gelada","value":9260,category:"Sem categoria"},
            {"x":"n","value":8680,category:"Sem categoria"},
            {"x":"flocos","value":8679,category:"Sem categoria"},
            {"x":"calabresa","value":8647,category:"Sem categoria"},
            {"x":"vou","value":7633,category:"Sem categoria"},
            {"x":"guarana","value":7554,category:"Sem categoria"},
            {"x":"gosto","value":7549,category:"Sem categoria"},
            {"x":"bom","value":7451,category:"Sem categoria"},
            {"x":"ta","value":7263,category:"Sem categoria"},
            {"x":"amargo","value":7169,category:"Características dos produtos"},
            {"x":"tudo","value":7064,category:"Sem categoria"},
            {"x":"brigadeiro","value":6931,category:"Hábito de consumo"},
            {"x":"todas","value":6776,category:"Sem categoria"},
            {"x":"melancia","value":6478,category:"Hábito de consumo"},
            {"x":"queria","value":6305,category:"Sem categoria"},
            {"x":"cafe","value":6271,category:"Hábito de consumo"},
            {"x":"comida","value":6169,category:"Sem categoria"},
            {"x":"fiz","value":6089,category:"Sem categoria"},
            {"x":"acai","value":6030,category:"Hábito de consumo"},
            {"x":"manga","value":6009,category:"Hábito de consumo"},
            {"x":"todos","value":5950,category:"Sem categoria"},
            {"x":"bem","value":5936,category:"Sem categoria"},
            {"x":"pq","value":5759,category:"Sem categoria"},
            {"x":"vontade","value":5719,category:"Sem categoria"},
            {"x":"ninho","value":5708,category:"Sem categoria"},
            {"x":"meio","value":5699,category:"Sem categoria"},
            {"x":"ai","value":5538,category:"Sem categoria"},
            {"x":"pure","value":5533,category:"Sem categoria"},
            {"x":"passada","value":5479,category:"Sem categoria"},
            {"x":"amo","value":5457,category:"Sem categoria"},
            {"x":"mal","value":5233,category:"Sem categoria"},
            {"x":"melhor","value":5203,category:"Sem categoria"},
            {"x":"jeito","value":5169,category:"Sem categoria"},
            {"x":"vai","value":5107,category:"Sem categoria"},
            {"x":"po","value":5001,category:"Sem categoria"},
            {"x":"todo","value":4953,category:"Sem categoria"},
            {"x":"dia","value":4792,category:"Sem categoria"},
            {"x":"tomar","value":4775,category:"Sem categoria"},
            {"x":"agora","value":4599,category:"Sem categoria"},
            {"x":"queijos","value":4599,category:"Sem categoria"},
            {"x":"fanta","value":4577,category:"Sem categoria"},
            {"x":"requeijao","value":4567,category:"Hábito de consumo"},
            {"x":"faz","value":4527,category:"Sem categoria"},
            {"x":"vc","value":4523,category:"Sem categoria"},
            {"x":"comendo","value":4494,category:"Sem categoria"},
            {"x":"presunto","value":4493,category:"Hábito de consumo"},
            {"x":"aqui","value":4430,category:"Sem categoria"},
            {"x":"barriga","value":4428,category:"Sem categoria"},
            {"x":"mim","value":4426,category:"Sem categoria"},
            {"x":"bacon","value":4374,category:"Hábito de consumo"},
            {"x":"menos","value":4361,category:"Sem categoria"},
            {"x":"milho","value":4285,category:"Hábito de consumo"},
            {"x":"casa","value":4253,category:"Sem categoria"},
            {"x":"mae","value":4155,category:"Sem categoria"},
            {"x":"massa","value":4136,category:"Sem categoria"},
            {"x":"picanha","value":4083,category:"Hábito de consumo"},
            {"x":"ser","value":4045,category:"Sem categoria"},
            {"x":"maca","value":3937,category:"Hábito de consumo"},
            {"x":"sei","value":3880,category:"Sem categoria"},
            {"x":"hoje","value":3784,category:"Sem categoria"},
            {"x":"gente","value":3743,category:"Sem categoria"},
            {"x":"coco","value":3642,category:"Hábito de consumo"},
            {"x":"comi","value":3574,category:"Sem categoria"},
            {"x":"goiaba","value":3570,category:"Hábito de consumo"},
            {"x":"cobertura","value":3543,category:"Sem categoria"},
            {"x":"coisa","value":3526,category:"Sem categoria"},
            {"x":"p","value":3502,category:"Sem categoria"},
            {"x":"feijao","value":3388,category:"Hábito de consumo"},
            {"x":"tanto","value":3382,category:"Sem categoria"},
            {"x":"pepsi","value":3381,category:"Sem categoria"},
            {"x":"quero","value":3353,category:"Sem categoria"},
            {"x":"mundo","value":3247,category:"Sem categoria"},
            {"x":"fica","value":3233,category:"Sem categoria"},
            {"x":"la","value":3227,category:"Sem categoria"},
            {"x":"tipo","value":3219,category:"Sem categoria"},
            {"x":"gosta","value":3207,category:"Sem categoria"},
            {"x":"ne","value":3184,category:"Sem categoria"},
            {"x":"portuguesa","value":3180,category:"Sem categoria"},
            {"x":"torta","value":3179,category:"Sem categoria"},
            {"x":"comprar","value":3116,category:"Sem categoria"},
            {"x":"mt","value":3042,category:"Sem categoria"},
            {"x":"macarrao","value":3031,category:"Hábito de consumo"},
            {"x":"sim","value":3013,category:"Sem categoria"},
            {"x":"nenhum","value":3012,category:"Sem categoria"},
            {"x":"miojo","value":2974,category:"Hábito de consumo"},
            {"x":"come","value":2974,category:"Sem categoria"},
            {"x":"negro","value":2970,category:"Sem categoria"},
            {"x":"normal","value":2955,category:"Sem categoria"},
            {"x":"assada","value":2938,category:"Sem categoria"},
            {"x":"pote","value":2914,category:"Sem categoria"},
            {"x":"diamante","value":2878,category:"Sem categoria"},
            {"x":"coisas","value":2870,category:"Sem categoria"},
            {"x":"ovo","value":2835,category:"Hábito de consumo"},
            {"x":"strogonoff","value":2814,category:"Hábito de consumo"},
            {"x":"tava","value":2781,category:"Sem categoria"},
            {"x":"ainda","value":2767,category:"Sem categoria"},
            {"x":"acho","value":2751,category:"Sem categoria"},
            {"x":"eh","value":2741,category:"Sem categoria"},
            {"x":"baunilha","value":2704,category:"Sem categoria"},
            {"x":"brocolis","value":2675,category:"Hábito de consumo"},
            {"x":"natural","value":2669,category:"Características dos produtos"},
            {"x":"nunca","value":2668,category:"Sem categoria"},
            {"x":"ter","value":2622,category:"Sem categoria"},
            {"x":"cola","value":2589,category:"Sem categoria"},
            {"x":"nada","value":2538,category:"Sem categoria"},
            {"x":"ponto","value":2523,category:"Sem categoria"},
            {"x":"molho","value":2512,category:"Sem categoria"},
            {"x":"minas","value":2476,category:"Sem categoria"},
            {"x":"ficou","value":2450,category:"Sem categoria"},
            {"x":"tao","value":2450,category:"Sem categoria"},
            {"x":"coalho","value":2429,category:"Sem categoria"},
            {"x":"deus","value":2378,category:"Sem categoria"},
            {"x":"kiwi","value":2378,category:"Hábito de consumo"},
            {"x":"goiabada","value":2369,category:"Hábito de consumo"},
            {"x":"tapioca","value":2352,category:"Hábito de consumo"},
            {"x":"oreo","value":2349,category:"Sem categoria"},
            {"x":"preto","value":2337,category:"Sem categoria"},
            {"x":"menta","value":2336,category:"Sem categoria"},
            {"x":"pode","value":2330,category:"Sem categoria"},
            {"x":"faca","value":2328,category:"Sem categoria"},
            {"x":"pastel","value":2215,category:"Sem categoria"},
            {"x":"ficar","value":2205,category:"Sem categoria"},
            {"x":"alho","value":2205,category:"Hábito de consumo"},
            {"x":"fazendo","value":2198,category:"Sem categoria"},
            {"x":"acucar","value":2151,category:"Hábito de consumo"},
            {"x":"verde","value":2129,category:"Sem categoria"},
            {"x":"d","value":2127,category:"Sem categoria"},
            {"x":"acerola","value":2123,category:"Hábito de consumo"},
            {"x":"assim","value":2113,category:"Sem categoria"},
            {"x":"ir","value":2092,category:"Sem categoria"},
            {"x":"kkkk","value":2059,category:"Sem categoria"},
            {"x":"iogurte","value":2056,category:"Hábito de consumo"},
            {"x":"sempre","value":2048,category:"Sem categoria"},
            {"x":"pudim","value":2046,category:"Hábito de consumo"},
            {"x":"vida","value":2029,category:"Sem categoria"},
            {"x":"ralado","value":2023,category:"Sem categoria"},
            {"x":"manha","value":2018,category:"Sem categoria"},
            {"x":"amendoim","value":2011,category:"Hábito de consumo"},
            {"x":"fez","value":1998,category:"Sem categoria"},
            {"x":"cuscuz","value":1986,category:"Hábito de consumo"},
            {"x":"cara","value":1985,category:"Hábito de consumo"},
            {"x":"tomate","value":1979,category:"Hábito de consumo"},
            {"x":"quente","value":1962,category:"Sem categoria"},
            {"x":"marguerita","value":1957,category:"Sem categoria"},
            {"x":"napolitano","value":1954,category:"Sem categoria"},
            {"x":"cheddar","value":1930,category:"Sem categoria"},
            {"x":"s","value":1905,category:"Sem categoria"},
            {"x":"lasanha","value":1862,category:"Hábito de consumo"},
            {"x":"uns","value":1838,category:"Sem categoria"},
            {"x":"pai","value":1830,category:"Sem categoria"},
            {"x":"pistache","value":1805,category:"Hábito de consumo"},
            {"x":"bolinha","value":1799,category:"Sem categoria"},
            {"x":"tomando","value":1793,category:"Sem categoria"},
            {"x":"nutella","value":1792,category:"Sem categoria"},
            {"x":"tomo","value":1780,category:"Sem categoria"},
            {"x":"frutas","value":1772,category:"Sem categoria"},
            {"x":"sabor","value":1769,category:"Sem categoria"},
            {"x":"nenhuma","value":1758,category:"Sem categoria"},
            {"x":"brownie","value":1756,category:"Sem categoria"},
            {"x":"receita","value":1752,category:"Sem categoria"},
            {"x":"quase","value":1745,category:"Sem categoria"},
            {"x":"churrasco","value":1739,category:"Hábito de consumo"},
            {"x":"ver","value":1722,category:"Sem categoria"},
            {"x":"figado","value":1716,category:"Hábito de consumo"},
            {"x":"comprei","value":1714,category:"Sem categoria"},
            {"x":"hortela","value":1701,category:"Hábito de consumo"},
            {"x":"recheada","value":1696,category:"Sem categoria"},
            {"x":"mousse","value":1694,category:"Hábito de consumo"},
            {"x":"entao","value":1691,category:"Sem categoria"},
            {"x":"cima","value":1690,category:"Sem categoria"},
            {"x":"kkkkk","value":1683,category:"Sem categoria"},
            {"x":"dois","value":1678,category:"Sem categoria"},
            {"x":"file","value":1675,category:"Hábito de consumo"},
            {"x":"peixe","value":1674,category:"Sem categoria"},
            {"x":"deu","value":1667,category:"Sem categoria"},
            {"x":"recheio","value":1657,category:"Sem categoria"},
            {"x":"pipoca","value":1649,category:"Hábito de consumo"},
            {"x":"pro","value":1648,category:"Sem categoria"},
            {"x":"cebola","value":1635,category:"Hábito de consumo"},
            {"x":"mao","value":1624,category:"Sem categoria"},
            {"x":"hj","value":1599,category:"Sem categoria"},
            {"x":"mano","value":1597,category:"Sem categoria"},
            {"x":"hamburguer","value":1585,category:"Hábito de consumo"},
            {"x":"prefiro","value":1584,category:"Sem categoria"},
            {"x":"vez","value":1583,category:"Sem categoria"},
            {"x":"arroz","value":1581,category:"Hábito de consumo"},
            {"x":"quarentena","value":1566,category:"Sem categoria"},
            {"x":"qlqr","value":1566,category:"Sem categoria"},
            {"x":"pamonha","value":1562,category:"Hábito de consumo"},
            {"x":"demais","value":1540,category:"Sem categoria"},
            {"x":"bife","value":1537,category:"Sem categoria"},
            {"x":"tbm","value":1536,category:"Sem categoria"},
            {"x":"sabe","value":1533,category:"Sem categoria"},
            {"x":"coloca","value":1532,category:"Sem categoria"},
            {"x":"cm","value":1524,category:"Sem categoria"},
            {"x":"vinho","value":1514,category:"Hábito de consumo"},
            {"x":"colocar","value":1511,category:"Sem categoria"},
            {"x":"ia","value":1490,category:"Sem categoria"},
            {"x":"agr","value":1484,category:"Sem categoria"},
            {"x":"pouco","value":1479,category:"Sem categoria"},
            {"x":"sal","value":1476,category:"Hábito de consumo"},
            {"x":"mussarela","value":1474,category:"Sem categoria"},
            {"x":"delicia","value":1470,category:"Sem categoria"},
            {"x":"prestigio","value":1470,category:"Sem categoria"},
            {"x":"vem","value":1461,category:"Sem categoria"},
            {"x":"sprite","value":1461,category:"Sem categoria"},
            {"x":"boa","value":1431,category:"Sem categoria"},
            {"x":"hora","value":1427,category:"Sem categoria"},
            {"x":"quatro","value":1415,category:"Sem categoria"},
            {"x":"cacau","value":1400,category:"Hábito de consumo"},
            {"x":"amiga","value":1396,category:"Sem categoria"}
        ];
            // console.log(data)
            // create a tag (word) cloud chart
            chart = anychart.tagCloud(data);

            // set a chart title
            //chart.title('15 most spoken languages')
            // set an array of angles at which the words will be laid out
            chart.angles([0])

            // enable a color range
            chart.colorRange(true);
            // set the color range length
            chart.colorRange().length('80%');
            chart.background().fill({
                keys: ["#f4f6f9"],
            });
            // display the word cloud chart
            chart.container("wordcloud");
            chart.draw();

        function shareAsPng() {
            // Share chart as PNG image.
            chart.shareAsPng(function (response) {
                console.log(response)
                Swal.fire({
                    icon: 'success',
                    showCloseButton: true,
                    confirmButtonText: '<a style="color:white; text-decoration: none;" href="' +response+ '" target="_blank">Nuvem de palavras<i class="fas fa-external-link-alt pl-2"></i></a>',
                })
            });
        };
    </script>
    <script src="{{ asset('js/components/sweetAlert.js') }}"></script>
@endpush
